version: '3.8'

services:
  led-server:
    build: ./server
    container_name: led-control-server
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true